#!/bin/bash

source "/data/SetupHelper/CommonResources"


if [ $scriptAction == 'INSTALL' ] ; then
  logMessage "Installing additional relays"
  updateActiveFile  /etc/venus/gpio_list
fi


if [ $scriptAction == 'UNINSTALL' ] ; then
  echo "Uninstalling relays"
  restoreActiveFile  /etc/venus/gpio_list
fi


if $filesUpdated ; then
    restartGui=true
fi

endScript
